// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var NavLibrary = require("./NavLibrary.js");

var Config = /* module */[];

var ReactNavigation = NavLibrary.CreateNavigation(Config);

var StackNavigator = 0;

exports.Config = Config;
exports.ReactNavigation = ReactNavigation;
exports.StackNavigator = StackNavigator;
/* ReactNavigation Not a pure module */
